server:
  port: 8080

bridge:
  configs:
    - name: A
      bridge: queue
      proxyAddress: 127.0.0.1:1111
      targetAddress: 127.0.0.1:7777
      connectTimeout: 10
#      allowClients:
#        - 127.0.0.2
#        - 127.0.0.3
    - name: B
      bridge: queue
      proxyAddress: 127.0.0.1:3333
      targetAddress: 127.0.0.1:7777
      connectTimeout: 10
#      allowClients:
#        - 127.0.0.4
#        - 127.0.0.5

