server:
  port: 8080

proxy:
  name: A
  out: true
  proxyServer: 127.0.0.1:1111
  appServer: 127.0.0.1:7777
  connectTimeout: 10
  heartbeat: 30
  keepAlive: true
  allowClients:
    - 127.0.0.2
    - 127.0.0.3
  ssl:
    open: false
    needClientAuth: false
    keyStoreType: PCKS12
    keyStore: D:/KeyStore/keystore.p12
    keyStorePassword: 123456
    trustKeyStore:
    trustKeyStorePassword:
  sendType: DB

database:
  config:
    poolType: hikari
    databaseType: oracle
    url: jdbc:mysql://localhost:3306/study
    user: root
    password: 123456
    driverClass: com.mysql.jdbc.Driver
    outWriteInTable: outWriteIn
    InWriteOutTable: InWriteOut



#bridge:
#  configs:
#    - name: A
#      bridge: DB
#      proxyServer: 127.0.0.1:1111
#      appServer: 127.0.0.1:7777
#      connectTimeout: 10
#      heartbeat: 30
#      keepAlive: true
#      ssl:
#        open: true
#        needClientAuth: false
#        keyStoreType: PCKS12
#        keyStore: D:/KeyStore/keystore.p12
#        keyStorePassword: 123456
#        trustKeyStore:
#        trustKeyStorePassword:
#      allowClients:
#        - 127.0.0.2
#        - 127.0.0.3



